### ISSUE TITLE
Titles display incorrectly _08-hazardmethods.md

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazardmethods#4]
@MamadioCMCC 

Thanks for updating the documentation - I've deployed it at https://gfdrr.github.io/thinkhazardmethods now

At line 42 in _08-hazardmethods.md the title doesn't display correctly. The error occurs directly after a table. Subsequent titles also affected down to Water scarcity levels, though I suspect fixing the first will fix all.
![image](https://user-images.githubusercontent.com/12515042/49934939-9fef3080-fec7-11e8-929a-37a31724527d.png)

**Comment by matamadio** [comment]
Not sure why is happening, code seems fine in preview. I changed a bit that could mess up markup recognition, let's see if the pull fixes, otherwise I add a div.

**Comment by stufraser1** [comment]
fixed after patch2-fix
