### ISSUE TITLE
Missing tsunami images

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazardmethods#5]
Tsunami images are missing from thinkhazardmethods/source/images/posts/hazardmethods/
so dont appear in the text correctly

The appear in pdf as:
![image](https://user-images.githubusercontent.com/12515042/49935122-0ffdb680-fec8-11e8-9690-c1e58adee2bc.png)
_08-hazardmethods.md

**Comment by matamadio** [comment]
FIxed on pull request
